modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory (26 is current forge version)
license="GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/Alex-the-666/Citadel/issues" #optional
[[mods]] #mandatory
modId="citadel" #mandatory
version="1.11.1" #mandatory
displayName="Citadel" #mandatory
displayURL="https://github.com/Alex-the-666/Citadel" #optional
logoFile="citadel.png" #optional
credits="Gegy1000" #optional
authors="Alexthe666" #optional
description='''A shared code library for many of Alexthe666's mods. Code used from LLibrary with permission.'''